-- MySQL Script generated by MySQL Workbench
-- 11/16/16 19:12:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema npstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema npstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `npstore` DEFAULT CHARACTER SET utf8 ;
USE `npstore` ;

-- -----------------------------------------------------
-- Table `npstore`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npstore`.`clientes` (
  `rut` INT(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `f_nac` DATE NOT NULL,
  PRIMARY KEY (`rut`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `npstore`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npstore`.`compras` (
  `id` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `rut_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Compra_Cliente_idx` (`rut_cliente` ASC),
  CONSTRAINT `fk_Compra_Cliente`
    FOREIGN KEY (`rut_cliente`)
    REFERENCES `npstore`.`clientes` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `npstore`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npstore`.`productos` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT(11) NOT NULL,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `npstore`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npstore`.`detalle` (
  `productos_id` INT(11) NOT NULL,
  `compras_id` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  PRIMARY KEY (`productos_id`, `compras_id`),
  INDEX `fk_productos_has_compras_compras1_idx` (`compras_id` ASC),
  INDEX `fk_productos_has_compras_productos1_idx` (`productos_id` ASC),
  CONSTRAINT `fk_productos_has_compras_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `npstore`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_compras_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `npstore`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
